<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Administrador.aspx.cs" Inherits="Vistas.Administrador" %>
<%@ Register Assembly="System.Web.Extensions, Version=1.0.61025.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" Namespace="System.Web.Script.Services" TagPrefix="asp" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>El Taller de Mati</title>
 
    <link rel="stylesheet" type="text/css" href="styles.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js"></script>
    
   
    <!-- Incluye tu archivo JavaScript compartido -->
   <script>
       function showAlert(message, icon = 'success') {
           Swal.fire({
               text: message,
               icon: icon,
               showConfirmButton: false,
               timer: 2000,
               timerProgressBar: false
           });
       }

       function showObservationPrompt(dni, dia, patente, chkbAsistencia) {
           Swal.fire({
               title: 'Ingrese las observaciones para el Cliente: ' + dni,
               input: 'textarea',
               inputPlaceholder: 'Escribe tus observaciones aquí...',
               showCancelButton: true,
               inputValidator: (value) => {
                   if (!value) {
                       return '¡Debes escribir algo!'
                   }
               }
           }).then((result) => {
               if (result.isConfirmed) {
                   // Llama al método del servidor para guardar la observación
                   PageMethods.GuardarObservacion(dni, dia, patente, result.value, onSuccess, onError);
               } else {
                   // Si no se ingresa observación, desmarcar el checkbox
                   document.getElementById(chkbAsistencia).checked = false;
               }
           });
       }

       function onSuccess() {
           showAlert("Observación guardada correctamente");
       }

       function onError(error) {
           showAlert("Error al guardar observación: " + error.get_message(), 'error');
       }

       // Asegúrate de que las funciones estén disponibles después de una solicitud asincrónica
       Sys.WebForms.PageRequestManager.getInstance().add_endRequest(function () {
           window.showAlert = showAlert;
           window.showObservationPrompt = showObservationPrompt;
       });
      
   </script> <!-- Asegúrate de que la ruta es correcta -->

    <style type="text/css">
        .auto-style11 {
            display: inline-block;
            width: 100%; /* Ajusta el ancho según sea necesario */;
            max-width: 100%; /* Máximo 100% del contenedor */;
            box-sizing: border-box;
            margin: 0 auto 0 0px;
            padding: 0;
        }
    </style>

</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server" EnablePageMethods="true" />
        <header>
            <div class="logo">
                <img src="Imagenes/logo.png" alt="Logo"/>
                <h1>El Taller de Mati</h1>
            </div>
            <nav>
                <a href="#">
                <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/Inicio.aspx">Salir</asp:HyperLink>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Label ID="lblUsuarioLogueado" runat="server" Font-Bold="True" ForeColor="White"></asp:Label>
                 </a>&nbsp;</nav>
        </header>
        <div class="container">
           <section class="intro">
    <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Underline="True" ForeColor="#0033CC" Text="TURNOS ASIGNADOS"></asp:Label>
    <br />
    <br />
    <asp:Button ID="btnAsignarTurno" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="Asignar Turno" OnClick="btnAsignarTurno_Click" />
    <br />
    <br />
    <div class="container">
        <div class="gv-container">
            <asp:GridView ID="gvTurnosAsignados" CssClass="auto-style11" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" OnRowDeleting="gvTurnosAsignados_RowDeleting" CellPadding="4" ForeColor="#333333" GridLines="None" AllowPaging="True">
    <AlternatingRowStyle BackColor="White" />
    <Columns>
        <asp:TemplateField HeaderText="N° de Turno">
            <ItemTemplate>
                <asp:Label ID="lblNTurno" runat="server" Text='<%# Eval("Id_Turno_T") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Fecha">
            <ItemTemplate>
                <asp:Label ID="lblDia" runat="server" Text='<%# Eval("Dia_T") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Hora">
            <ItemTemplate>
                <asp:Label ID="lblHora" runat="server" Text='<%# Eval("Hora_T") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Nombre">
            <ItemTemplate>
                <asp:Label ID="lblNombre" runat="server" Text='<%# Eval("Nombre_CLI") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Marca">
            <ItemTemplate>
                <asp:Label ID="lblMarca" runat="server" Text='<%# Eval("Marca_M") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Modelo">
            <ItemTemplate>
                <asp:Label ID="lblModelo" runat="server" Text='<%# Eval("Modelo_M") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Servicio">
            <ItemTemplate>
                <asp:Label ID="lblServicio" runat="server" Text='<%# Eval("Nombre_S") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Observacion">
            <ItemTemplate>
                <asp:Label ID="lblObservacion" runat="server" Text='<%# Eval("Observacion_T") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>

         <asp:TemplateField HeaderText="Asistencia">
                    <ItemTemplate>
                        <asp:CheckBox ID="chkbAsistencia" runat="server" Checked='<%# Eval("Asistencia_T") %>' OnCheckedChanged="CheckBox1_CheckedChanged"  AutoPostBack="True"/>
                    </ItemTemplate>
                </asp:TemplateField>

         <asp:TemplateField HeaderText="Kilometraje">
            <ItemTemplate>
                <asp:TextBox ID="txtKilometraje" runat="server" TextMode="Number"></asp:TextBox>
            </ItemTemplate>
        </asp:TemplateField>

    </Columns>
    <EditRowStyle BackColor="#2461BF" />
    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
    <RowStyle BackColor="#EFF3FB" />
    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
    <SortedAscendingCellStyle BackColor="#F5F7FB" />
    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
    <SortedDescendingCellStyle BackColor="#E9EBEF" />
    <SortedDescendingHeaderStyle BackColor="#4870BE" />
</asp:GridView>

        </div>
    </div>
</section>

            <section class="intro">
                <asp:Label ID="Label2" runat="server" Font-Bold="True" Font-Underline="True" ForeColor="#0033CC" Text="SERVICIOS"></asp:Label>
                <br />
                <br />
                <asp:Button ID="btnAgregarServicio" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="Agregar Servicio" OnClick="btnAgregarServicio_Click" />
                <br />
                <br />
                <div class="container">
                <div class="gv-container">
                    <asp:GridView ID="gvServicios" CssClass="auto-style10" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" GridLines="None" Width="780px" AllowPaging="True" AutoGenerateEditButton="True" ShowFooter="True" AllowSorting="True" OnRowDeleting="gvServicios_RowDeleting" OnRowEditing="gvServicios_RowEditing" OnRowUpdating="gvServicios_RowUpdating" OnRowCancelingEdit="gvServicios_RowCancelingEdit">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:TemplateField HeaderText="Id Servicio">
                                <EditItemTemplate>
                                    <asp:Label ID="lbletIdServicio" runat="server" Text='<%# Eval("Id_Servicio_S") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblIdServicio" runat="server" Text='<%# Eval("Id_Servicio_S") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Nombre">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtetNombre" runat="server" Text='<%# Eval("Nombre_S") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblNombre" runat="server" Text='<%# Eval("Nombre_S") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Detalle">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtetDetalle" runat="server" Text='<%# Eval("Detalle_S") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblDetalle" runat="server" Text='<%# Eval("Detalle_S") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Precio">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtetPrecio" runat="server" Text='<%# Eval("Precio_S") %>' TextMode="Number"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblPrecio" runat="server" Text='<%# Eval("Precio_S") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>
                </div>
                      </div>
                <br />
                <br />
            </section>
            <section class="intro">
                <asp:Button ID="btnCliXMotos" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="VER CLIENTES Y MOTOS" OnClick="btnCliXMotos_Click" />
                <br />
                <br />
                <asp:Button ID="btnHistorial" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="HISTORIAL" PostBackUrl="~/Historial.aspx" />
                <br />
                <br />
                <asp:Button ID="btnIngresarFechas" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="INGRESAR FECHAS PARA TURNOS" OnClick="btnIngresarFechas_Click" />
                <br />
                <br />
            </section>
        </div>
    </form>
</body>
</html>
