<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Administrador.aspx.cs" Inherits="Vistas.Administrador" %>


<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>El Taller de Mati</title>
    <link rel="stylesheet" type="text/css" href="styles.css" />
    <style type="text/css">
        .auto-style9 {
            display: inline-block;
            margin: 0 auto;
        }
    </style>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Incluye tu archivo JavaScript compartido -->
    <script src="sweetalert.js"></script>
</head>
<body>
    <form id="form1" runat="server">
        <header>
            <div class="logo">
                <img src="Imagenes/logo.png" alt="Logo">
                <h1>El Taller de Mati</h1>
            </div>
            <nav>
                <a href="#">
                <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/Inicio.aspx">Salir</asp:HyperLink>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Label ID="lblUsuarioLogueado" runat="server" Font-Bold="True" ForeColor="White">USUARIO LOGUEADO</asp:Label>
                 </a>&nbsp;</nav>
        </header>
        <div class="container">
           <section class="intro">
    <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Underline="True" ForeColor="#0033CC" Text="TURNOS ASIGNADOS"></asp:Label>
    <br />
    <br />
    <asp:Button ID="btnAsignarTurno" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="Asignar Turno" PostBackUrl="~/ReservarTurno.aspx" />
               <asp:Label ID="Label3" runat="server"></asp:Label>
    <br />
    <br />
    <div class="container">
        <div class="gv-container">
            <asp:GridView ID="gvTurnosAsignados" CssClass="Gv" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" OnRowDeleting="gvTurnosAsignados_RowDeleting" CellPadding="4" ForeColor="#333333" GridLines="None" AllowPaging="True">
    <AlternatingRowStyle BackColor="White" />
    <Columns>
        <asp:TemplateField HeaderText="N° de Turno">
            <ItemTemplate>
                <asp:Label ID="lblNTurno" runat="server" Text='<%# Eval("Id_Turno_T") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Fecha">
            <ItemTemplate>
                <asp:Label ID="lblDia" runat="server" Text='<%# Eval("Dia_T") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Hora">
            <ItemTemplate>
                <asp:Label ID="lblHora" runat="server" Text='<%# Eval("Hora_T") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Nombre">
            <ItemTemplate>
                <asp:Label ID="lblNombre" runat="server" Text='<%# Eval("Nombre_CLI") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Marca">
            <ItemTemplate>
                <asp:Label ID="lblMarca" runat="server" Text='<%# Eval("Marca_M") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Modelo">
            <ItemTemplate>
                <asp:Label ID="lblModelo" runat="server" Text='<%# Eval("Modelo_M") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Servicio">
            <ItemTemplate>
                <asp:Label ID="lblServicio" runat="server" Text='<%# Eval("Nombre_S") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Observacion">
            <ItemTemplate>
                <asp:Label ID="lblObservacion" runat="server" Text='<%# Eval("Observacion_T") %>'></asp:Label>
            </ItemTemplate>
        </asp:TemplateField>

         <asp:TemplateField HeaderText="Asistencia">
                    <ItemTemplate>
                        <asp:CheckBox ID="chkbAsistencia" runat="server" Checked='<%# Eval("Asistencia_T") %>' OnCheckedChanged="CheckBox1_CheckedChanged"  AutoPostBack="True"/>
                    </ItemTemplate>
                </asp:TemplateField>

    </Columns>
    <EditRowStyle BackColor="#2461BF" />
    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
    <RowStyle BackColor="#EFF3FB" />
    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
    <SortedAscendingCellStyle BackColor="#F5F7FB" />
    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
    <SortedDescendingCellStyle BackColor="#E9EBEF" />
    <SortedDescendingHeaderStyle BackColor="#4870BE" />
</asp:GridView>

        </div>
    </div>
</section>

            <section class="intro">
                <asp:Label ID="Label2" runat="server" Font-Bold="True" Font-Underline="True" ForeColor="#0033CC" Text="SERVICIOS"></asp:Label>
                <br />
                <br />
                <asp:Button ID="btnAgregarServicio" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="Agregar Servicio" />
                <br />
                <br />
                <div class="gv-container">
                    <asp:GridView ID="gvMisTurnos" CssClass="Gv" runat="server" AutoGenerateDeleteButton="True">
                    </asp:GridView>
                </div>
                <br />
                <br />
            </section>
            <section class="intro">
                <asp:Button ID="btnCliXMotos" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="VER CLIENTES Y MOTOS" />
                <br />
                <br />
                <asp:Button ID="btnHistorial" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="HISTORIAL" />
                <br />
                <br />
                <asp:Button ID="btnIngresarFechas" runat="server" Font-Bold="True" ForeColor="#0033CC" Text="INGRESAR FECHAS PARA TURNOS" />
                <br />
                <br />
            </section>
        </div>
    </form>
</body>
</html>
